CodeSystem: TestTypeCS
Id: test-type-cs
Title: "Test Type Code System"
Description: "Code system for test types."

* #AESCULINE_DIHYDROLASE_TEST "Aesculine dihydrolase test"
* #AGAR_GEL_IMMUNODIFFUSION_(AGID) "Agar-gel immunodiffusion (AGID)"
* #AGAR_GEL_PRECIPITATION_(AGP) "Agar-gel precipitation (AGP)"
* #ANATOMO_PATHOLOGICAL_EXAMINATION "Anatomo-pathological examination"
* #ANTIBODY_DETECTION_ELISA "Antibody detection ELISA"
* #ANTIGEN_DETECTION_ELISA "Antigen detection ELISA"
* #ARGININE_DIHYDROLASE_TEST "Arginine dihydrolase test"
* #BACTERIOLOGICAL_EXAMINATION "Bacteriological examination"
* #BRUCELLOSIS_TEST "Brucellosis test"
* #BSE_ANTIGEN_TEST_KIT "BSE Antigen Test kit"
* #BUFFY_COAT_EXAMINATION "Buffy coat examination"
* #BUTTER_FAT_TEST "Butter fat test"
* #CALCIUM_TEST_IN_FEED "Calcium test in feed"
* #CARBOHYDRATE_FERMINTATION_TEST "Carbohydrate fermintation test"
* #CASEIN_HYDROLYSIS_TEST "Casein hydrolysis test"
* #CATALASE_TEST "Catalase test"
* #CENTRIFUGATION_TEST "Centrifugation test"
* #CITRATE_TESTVOGES_PROSKAEUR_TEST "Citrate testVoges proskaeur test"
* #COAGULATE_TEST "Coagulate test"
* #COGGIN'S_TEST "Coggin's test"
* #COMPETITIVE_ELISA_(C_ELISA) "Competitive ELISA (c-ELISA)"
* #COMPLEMENT_FIXATION_TEST_(CFT) "Complement fixation test (CFT)"
* #CULTURE_FOR_MYCOPLASMA "Culture for Mycoplasma"
* #DET_BIRBRIGHT "Det Birbright"
* #DIRECT_FLUORESCENT_ANTIBODY_(FAT)_TEST "Direct fluorescent antibody (FAT) test"
* #DIRECT_IMMUNOFLUORESCENCE_(DIF) "Direct immunofluorescence (DIF)"
* #DIRECT_RAPID_IMMUNOHISTOCHEMICAL_TEST_(DRIT) "Direct rapid immunohistochemical test (DRIT)"
* #DIRECT_SMEAR_EXAMINATION "Direct smear examination"
* #EGG_INOCULATON "Egg inoculaton"
* #ELECTROIMMUNOTRANSFER_BLOT_ASSAY_(EITB) "Electroimmunotransfer blot assay (EITB)"
* #ELECTRON_MICROSCOPY "Electron microscopy"
* #ELISA_3ABC "ELISA 3ABC"
* #ENTOMOLOGICAL_INVESTIGATIONS "Entomological investigations"
* #ENZYM_IMMUNOASSAY_(EIA)_MEMBRANE_TEST "Enzym immunoassay (EIA) membrane test"
* #ENZYME_LINKED_IMMUNOSORBENT_ASSAY_(ELISA) "Enzyme-linked immunosorbent assay (ELISA)"
* #FLOATATION_TEST "Floatation test"
* #FLUORESCENT_ANTIBODY_VIRUS "Fluorescent antibody virus"
* #FUORESCENCE_POLARISATION_ASSAY_(FPA) "Fuorescence polarisation assay (FPA)"
* #GELATIN_HYDROLYSIS_TEST "Gelatin hydrolysis test"
* #GENE_SEQUENCING "Gene sequencing"
* #GIEMSA_STAINING "Giemsa staining"
* #GLUCONATE_TEST "Gluconate test"
* #GRAM_STAINING "Gram staining"
* #HAEMAGGLUTINATION_(HA)_TEST "Haemagglutination (HA) test"
* #HAEMAGGLUTINATION_INHIBITION_TEST_(HIT) "Haemagglutination inhibition test (HIT)"
* #HISTOLOGICAL_TEST "Histological test"
* #HISTOPATHOLOGICAL_EXAMINATION "Histopathological examination"
* #IGG "IgG"
* #IGG_CAPTURE_ELISA "IgG-capture ELISA"
* #IGM "IgM"
* #IGM_CAPTURE_ELISA "IgM-capture ELISA"
* #IMMUNE_ELECTRON_MICROSCOPY "Immune electron microscopy"
* #IMMUNO_BLOTTING_(IB) "Immuno-blotting (IB)"
* #IMMUNOCAPTURE_ELISA "Immunocapture ELISA"
* #IMMUNOELECTROPHORESIS_TEST_(IEPT) "Immunoelectrophoresis test (IEPT)"
* #IMMUNOHISTOCHEMICAL_TEST "Immunohistochemical test"
* #IMMUNOPEROXIDASE_MONOLAYER_ASSAY_(IPMA) "Immunoperoxidase monolayer assay (IPMA)"
* #IN_SITU_HYBRIDISATION_(ISH) "In situ hybridisation (ISH)"
* #INDIRECT_ELISA "Indirect ELISA"
* #INDIRECT_FLUORESCENT_ANTIBODY_(IFA)_TEST "Indirect fluorescent antibody (IFA) test"
* #INDIRECT_SANDWICH_ELISA "Indirect sandwich ELISA"
* #INDOLE_TEST "Indole test"
* #INOCULATION_TEST "Inoculation test"
* #INTRACEREBRAL_PATHOGENICITY_INDEX_(ICPI)_TEST "Intracerebral pathogenicity index (ICPI) test"
* #INTRAVENOUS_PATHOGENICITY_INDEX_(IVPI)_TEST "Intravenous pathogenicity index (IVPI) test"
* #ISOENZYME_STUDIES "Isoenzyme studies"
* #IZSLER_AG "Izsler Ag"
* #IZSLER_ELISA "Izsler Elisa"
* #LIQUID_PHASE_(LP)_BLOCKING_ELISA "Liquid-phase (LP) blocking ELISA"
* #LUMINESCENCE_IMMUNOASSAY "Luminescence immunoassay"
* #LYSINE_DECARBOXYLATE_TEST "Lysine decarboxylate test"
* #MALLEIN_TEST "Mallein test"
* #MICROSCOPIC_AGGLUTINATION_TEST_(MAT) "Microscopic agglutination test (MAT)"
* #MICROSCOPIC_EXAMINATION "Microscopic examination"
* #MICROSCOPIC_EXAMINATION_OF_LARVAE "Microscopic examination of larvae"
* #MILK_DENSITY/MILK_QUALITY "Milk density/milk quality"
* #MONOCLONAL_ANTIBODIES_(MAB)_TEST "Monoclonal antibodies (Mab) test"
* #MOTILITY_TEST "Motility test"
* #MULTIPLEX_PCR "Multiplex PCR"
* #NESTED_RT_PCR "Nested RT-PCR"
* #NEURAMINIDASE_INHIBITION_ASSAY "Neuraminidase inhibition assay"
* #NEUTRALISATION_(FAVN) "Neutralisation (FAVN)"
* #NITRATE_REDUCTION_TEST "Nitrate reduction test"
* #NO_TEST_DONE "No test done"
* #NON_STRUCTURAL_PROTEIN_ELISA "Non-structural protein ELISA"
* #NOT_SPECIFIED_TEST "Not Specified Test"
* #NPLA_(NEUTRALISING_PEROXIDASE_LINKED_ASSAY) "NPLA (Neutralising peroxidase-linked assay)"
* #NUCLEOTIDE_SEQUENCING "Nucleotide sequencing"
* #OPTICAL_MICROSCOPY "Optical microscopy"
* #ORMITHIAMINE_DECARBOXYLASE_TEST "Ormithiamine decarboxylase test"
* #OXIDASE_TEST "Oxidase test"
* #PARASITOLOGICAL_EXAMINATION "Parasitological examination"
* #PATHOGEN_ISOLATION_BY_EGG_INOCULATION "Pathogen isolation by egg inoculation"
* #PATHOGEN_ISOLATION_ON_CELL_CULTURE "Pathogen isolation on cell culture"
* #PH_TEST_(_FEEDSSEMEN) "PH test ( feeds,semen)"
* #PHYLOGENETIC_ANALYSIS "Phylogenetic analysis"
* #PLAQUE_REDUCTION_NEUTRALISATION_TEST_(PRN) "Plaque reduction neutralisation test (PRN)"
* #POLYMERASE_CHAIN_REACTION_(PCR) "Polymerase chain reaction (PCR)"
* #PROXIMATE_ANALYSIS "Proximate analysis (protein,fat,NFE,fiber and moisture)"
* #RAPID_AGGULUTINATION_TEST "Rapid aggulutination test"
* #RAPID_SERUM_AGGLUTINATION_(RSA) "Rapid serum agglutination (RSA)"
* #RAPID_TESTS "Rapid tests"
* #REAL_TIME_PCR "Real-time PCR"
* #REAL_TIME_REVERSE_TRANSCRIPTASE/POLYMERASE "Real-time reverse transcriptase/polymerase chain reaction (RRT-PCR)"
* #REVERSE_TRANSCRIPTION__POLYMERASE_CHAIN_REACTION "Reverse transcription - polymerase chain reaction"
* #ROSE_BENGAL_TEST_(RBT) "Rose bengal test (RBT)"
* #SELLER'S_TEST "Seller's test"
* #SEMEN_EXAMINATION "Semen examination"
* #SERONEUTRALISATION_TEST_(SNT) "Seroneutralisation test (SNT)"
* #SEROTYPING "Serotyping"
* #SERUM_AGGLUTINATION_TEST "Serum agglutination test"
* #TISSUE_IMPRINTS "Tissue imprints"
* #TRIPLE_SUGAR_IRON_AGAR_TEST "Triple sugar iron agar test"
* #TUBE_AGGLUTINATION_TEST_(TAT) "Tube agglutination test (TAT)"
* #TYPING_ELISA "Typing ELISA"
* #UREASE_TEST "Urease test"
* #VIRUS_ISOLATION "Virus isolation"
* #VIRUS_NEUTRALISATION_TEST_(VNT) "Virus neutralisation test (VNT)"
* #VIRUS_SEQUENCING "Virus sequencing"
* #VIRUS_INFECTION_ASSOCIATED_ANTIGEN_(VIAA) "Virus-infection-associated antigen (VIAA)"
* #WESTERN_BLOT_ANALYSIS "Western blot analysis"
* #WESTERN_BLOTTING_(WB) "Western blotting (WB)"
* #ZIEHL_NEELSEN_TEST "Ziehl Neelsen test"
* #RTPCR "Reverse transcription - polymerase chain reaction (RT-PCR)"
