CodeSystem: AnimalSpeciesCS
Id: animal-species-cs
Title: "Animal Species Code System"
Description: "Code system representing various animal species."
* #ABALONES "Abalones"
* #ACCIPITER_GENTILIS "Accipiter gentilis"
* #ACCIPITRIDAE_(INCOGNITA) "Accipitridae (incognita)"
* #ACCIPITRIDAE_UNIDENTIFIED_ACCIPITRIDAE_INCOGNITA "Accipitridae (unidentified):Accipitridae (incognita)(Accipitridae)"
* #AFRICAN_BLACK_OYSTERCATCHER_(HAEMATOPUS_MOQUINI) "African black Oystercatcher (Haematopus moquini)"
* #AFRICAN_FISH_EAGLE_(HALIAEETUS_VOCIFER) "African fish eagle (Haliaeetus vocifer)"
* #AFRICAN_GOSHAWK "African goshawk"
* #AFRICAN_JACANA "African Jacana"
* #AFRICAN_MASKED_WEAVER_(PLOCEUS_VELATUS) "African masked weaver (Ploceus velatus)"
* #AFRICAN_PENGUIN_(SPHENISCUS_DEMERSUS) "African penguin (Spheniscus demersus)"
* #AFRICAN_RABBIT_(ORYCTOLAGUS_CUNICULUS) "African Rabbit (Oryctolagus cuniculus)"
* #AFRICAN_RAIL "African Rail"
* #AFRICAN_SACRED_IBIS_(THRESKIORNIS_AETHIOPICUS) "African sacred ibis (Threskiornis aethiopicus)"
* #AFRICAN_YELLOW_WHITE_EYE "African Yellow White-eye"
* #ALLEN'S_GALLINULE "Allen's gallinule"
* #ALPACA "Alpaca"
* #AMERICAN_BADGER "American badger"
* #AMERICAN_CROW_(CORVUS_BRACHYRHYNCHOS) "American Crow (Corvus Brachyrhynchos)"
* #AMERICAN_GREEN_WINGED_TEAL "American Green-winged teal"
* #AMERICAN_OYSTERCATCHER "American Oystercatcher"
* #PELECANIDAE_PHAETHONTIFORMES "American White Pelican (Pelecanus erythrorhynchos):Pelecanidae-Phaethontiformes"
* #AMERICAN_WIGEON "American wigeon"
* #AMUR_TIGER "Amur Tiger"
* #ANATIDAE_(INCOGNITA) "Anatidae (incognita)"
* #ANSER_CAERULESCENS_(_SNOW_GOOSE_) "Anser caerulescens: ( snow goose )"
* #ANSERINAE "Anserinae (unidentified):Anserinae (incognita)(Anatidae)"
* #ANTELOPE "Antelope"
* #ANTILLEAN_MANATEE_(TRICHECUS_MANATUS_MANATUS) "Antillean manatee (Trichecus manatus manatus)"
* #APIS_MELLIFERA_LITOREA "Apis mellifera litorea"
* #ARCTIC_SKUA_(OR_PARASITIC_JAEGER) "Arctic skua (or parasitic jaeger)"
* #ARCTIC_TERN_(STERNA_PARADISEA) "Arctic tern (Sterna paradisea)"
* #ARDEIDAE_(UNSPECIFIED) "Ardeidae (unspecified)"
* #ARENARIA_INTERPRES "Arenaria interpres"
* #ARMENIAN_GULL_(LARUS_ARMENICUS) "Armenian gull (Larus armenicus)"
* #ASIAN_GOLDEN_WEAVER "Asian Golden Weaver"
* #ASIAN_OPENBILL "Asian Openbill"
* #ASIATIC_GOLDEN_CAT_(CATOPUMA_TEMMINCKII) "Asiatic golden cat (Catopuma temminckii)"
* #BABOON "Baboon"
* #BACTRIAN_CAMEL_(CAMELUS_BACTRIANUS) "Bactrian camel (Camelus bactrianus)"
* #BADGER "Badger"
* #BAILLON'S_CRAKE "Baillon's Crake"
* #BALD_EAGLE_(HALIAEETUS_LEUCOCEPHALUS) "Bald Eagle (Haliaeetus Leucocephalus)"
* #BANTENG_(BOS_JAVANICUS) "Banteng (Bos javanicus)"
* #BAR_BREASTED_FIREFINCH "Bar-breasted Firefinch"
* #BAR_HEADED_GOOSE "Bar-Headed Goose"
* #BARN_OWL_(TYTO_ALBA) "Barn owl (Tyto alba)"
* #BARN_SWALLOW "Barn Swallow"
* #BARNACLE_GOOSE_BRANTA_LEUCOPSIS(ANATIDAE) "Barnacle Goose:Branta leucopsis(Anatidae)"
* #BARRED_OWL_(STRIX_VARIA) "Barred owl (Strix varia)"
* #BAT "Bat"
* #BAT_EATING_LIZARD "Bat eating lizard"
* #BAYA_WEAVER "Baya Weaver"
* #BEAN_GOOSE_(ANSER_FABALIS) "Bean goose (Anser fabalis)"
* #BEAVER_(CASTOR) "Beaver (Castor)"
* #BEES_(HIVES) "Bees (hives)"
* #BERNIERS_TEAL_(ANAS_BERNIERI) "Berniers teal (Anas bernieri)"
* #BHARAL "Bharal"
* #BISON "Bison"
* #BIVALVES "Bivalves"
* #BLACK_BACKED_GULL_(LARUS_MARINUS) "Black backed gull (Larus marinus)"
* #BLACK_COLLARED_STARLING "Black collared starling"
* #BLACK_COUCAL "Black coucal"
* #BLACK_CRAKE "Black Crake"
* #BLACK_HEADED_GULL_(CHROICOCEPHALUS_RIDIBUNDUS) "Black headed gull (Chroicocephalus ridibundus)"
* #BLACK_RHINOCEROS "Black rhinoceros"
* #BLACK_SKIMMER "Black Skimmer"
* #BLACK_SWAN_CYGNUS_ATRATUS(ANATIDAE) "Black Swan:Cygnus atratus(Anatidae)"
* #BLACK_BACKED_JACKAL_(CANIS_MESOMELAS) "Black-backed jackal (Canis mesomelas)"
* #BLACK_BELLIED_PLOVER "Black-bellied Plover"
* #BLACK_BILLED_MAGPIE_(PICA_HUDSONIA)_ "Black-billed Magpie (Pica hudsonia):"
* #BLACK_BROWED_REED_WARBLER "Black-browed Reed Warbler"
* #BLACK_CAPPEDCHICKADEE "Black-cappedChickadee"
* #BLACK_FACED_SPOONBILL_(PLATALEA_MINOR) "Black-faced spoonbill (Platalea minor)"
* #BLACK_FOOTED_FERRET "Black-footed ferret"
* #BLACK_HEADED_GULL_LARIDAE_CHARADRIIFORMES "Black-headed Gull (Chroicocephalus ridibundus):Laridae-Charadriiformes"
* #BLACK_HEADED_HERON_(ARDEA_MELANOCEPHALA) "Black-headed heron (Ardea melanocephala)"
* #BLACK_HEADED_MUNIA "Black-headed Munia"
* #BLACK_LEGGED_KITTIWAKE "Black-legged Kittiwake (Rissa tridactyla):Laridae-Charadriiformes"
* #BLACK_NECKED_GREBE_(PODICEPS_NIGRICOLLIS) "Black-necked Grebe (Podiceps Nigricollis)"
* #BLACK_NECKED_SWAN_(CYGNUS_MELANCORYPHUS) "Black-necked swan (Cygnus melancoryphus)"
* #BLACK_TAILED_JACKRABBIT_(LEPUS_CALIFORNICUS) "Black-tailed Jackrabbit (Lepus californicus)"
* #BLACK_WINGED_STILT "Black-winged Stilt"
* #BLACKSMITH_LAPWING "Blacksmith Lapwing"
* #BLUE_SPOTTED_WOOD_DOVE "Blue -spotted wood dove"
* #BLUE_CRANE_(GRUS_PARADISEA) "Blue crane (Grus paradisea)"
* #BLUE_MONKEY "Blue monkey"
* #BLUE_QUAIL "Blue quail"
* #BONTEBOK "Bontebok"
* #BOOBY_(PELECANUS_LEUCOGASTER) "Booby (Pelecanus leucogaster)"
* #BORNEAN_BINTURONG "Bornean binturong"
* #BRANTA_RUFICOLLIS "Branta ruficollis"
* #BRAZILIAN_TEAL "Brazilian Teal"
* #BRENT_GOOSE_BRANTA_BERNICLA(ANATIDAE) "Brent Goose:Branta bernicla(Anatidae)"
* #BROWN_BABBLER "Brown Babbler"
* #BROWN_HARE "Brown Hare"
* #BROWN_PELICAN_(PELECANUS_OCCIDENTALIS) "Brown pelican (Pelecanus occidentalis)"
* #BROWN_HEADED_GULL_(CHROICOCEPHALUS_BRUNNICEPHALUS) "Brown-headed gull (Chroicocephalus brunnicephalus)"
* #BROWN_THROATED_MARTIN "Brown-throated Martin"
* #BUFF_SPOTTED_CRAKE "Buff spotted crake"
* #BUFFALOE "Buffaloe"
* #BUSARD_PÃ¢LE "Busard pÃ¢le"
* #BUSH_FOWL "Bush Fowl"
* #BUZZARD "Buzzard"
* #CACKLING_GOOSE "Cackling Goose"
* #CAMELIDAE_(UNIDENTIFIED) "Camelidae (unidentified)"
* #CANADA_GOOSE_BRANTA_CANADENSIS(ANATIDAE) "Canada Goose:Branta canadensis(Anatidae)"
* #CANADA_LYNX_(LYNX_CANADENSIS) "Canada lynx (Lynx canadensis)"
* #CANINE "Canine"
* #CAPE_CORMORANT_(PHALACROCORAX_CAPENSIS) "Cape cormorant (Phalacrocorax capensis)"
* #CAPE_GANNET_(MORUS_CAPENSIS) "Cape gannet (Morus capensis)"
* #CAPE_GANNET_SHY_ALBATROSS "Cape gannet Shy albatross"
* #CAPE_TEAL "Cape teal"
* #CAPTIVE_CATTLE_EGRETS "Captive cattle egrets"
* #CASMERODIU "Casmerodiu"
* #CASPIAN_SEAL_(PUSA_CASPICA) "Caspian seal (Pusa caspica)"
* #CATS "Cats"
* #CATTLE "Cattle"
* #CATTLE_EGRET "Cattle egret"
* #CERVIDAE "Cervidae"
* #CHARADRIIDAE "Charadriidae (unidentified):Charadriidae (incognita)(Charadriidae)"
* #CHARADRIUS_PALLIDUS "Charadrius pallidus"
* #CHEETAH "Cheetah"
* #CHICKEN "Chicken"
* #CHIMPANZEE_(PAN_TROGLODYTES) "Chimpanzee (Pan troglodytes)"
* #CHOUGH "Chough"
* #CICONIIDAE "Ciconiidae (unidentified):Ciconiidae(incognita)(Ciconiidae)"
* #CINNAMON_BITTERN "Cinnamon Bittern"
* #CINNAMON_TEAL "Cinnamon Teal"
* #CIVET "Civet"
* #CLAMOROUS_REED_WARBLER "Clamorous Reed Warbler"
* #COATI_(GEN_NASUA) "Coati (Gen. Nasua)"
* #COCKATIEL "Cockatiel"
* #COLLARED_PRATINCOLE "Collared Pratincole"
* #COLUMBIDAE "Columbidae (unidentified):Columbidae (incognita)(Columbidae)"
* #COMMON_BULBUL "Common Bulbul"
* #COMMON_BUTTONQUAIL "Common Buttonquail"
* #COMMON_CARP "Common Carp"
* #COMMON_CARP_(CYPRINUS_CARPIO) "Common carp (Cyprinus carpio)"
* #COMMON_COOT "Common coot"
* #COMMON_DUIKER_(SYLVICAPRA_GRIMMIA) "Common duiker (Sylvicapra grimmia)"
* #COMMON_EIDER_(SOMATERIA_MOLLISSIMA) "Common Eider (Somateria mollissima)"
* #COMMON_GOLDENEYE_BUCEPHALA_CLANGULA(ANATIDAE) "Common Goldeneye:Bucephala clangula(Anatidae)"
* #COMMON_GRACKLE "Common Grackle"
* #COMMON_GREENSHANK "Common Greenshank"
* #COMMON_IORA "Common Iora"
* #COMMON_KESTREL_FALCO_TINNUNCULUS(FALCONIDAE) "Common Kestrel:Falco tinnunculus(Falconidae)"
* #COMMON_KINGFISHER "Common Kingfisher"
* #COMMON_LOON_(GAVIA_IMMER) "Common loon (Gavia immer)"
* #COMMON_MOORHEN_(GALLINULA_CHLOROPUS) "Common moorhen (Gallinula chloropus)"
* #COMMON_MURRE_(URIA_AALGE) "Common murre (Uria aalge)"
* #COMMON_MYNA "Common Myna"
* #COMMON_PHEASANT_(PHASIANUS_COLCHICUS) "Common pheasant (Phasianus colchicus)"
* #COMMON_POCHARD_(AYTHYA_FERINA) "Common pochard (Aythya ferina)"
* #COMMON_QUAIL_COTURNIX_COTURNIX(PHASIANIDAE) "Common Quail:Coturnix coturnix(Phasianidae)"
* #COMMON_RAVEN_(CORVUS_CORAX) "Common Raven (Corvus corax)"
* #COMMON_REDSHANK "Common Redshank"
* #COMMON_RINGED_PLOVER "Common ringed plover"
* #COMMON_SANDPIPER "Common sandpiper"
* #COMMON_SHELDUCK_(TADORNA_TADORNA) "Common shelduck (Tadorna tadorna)"
* #COMMON_SNIPE "Common snipe"
* #COMMON_TERN_(STERNA_HIRUNDO) "Common Tern (Sterna hirundo)"
* #COMMON_WOOD_PIGEON_COLUMBA_PALUMBUS(COLUMBIDAE) "Common Wood-Pigeon:Columba palumbus(Columbidae)"
* #CONDOR "Condor"
* #CONEJO "conejo"
* #COOPER'S_HAWK "Cooper's hawk"
* #CORMORANT "Cormorant"
* #CORN_CRAKE "Corn crake"
* #CORVUS_BRACHYRHYNCHOS_(CORVIDAE)_AMERICAN_CROW "Corvus brachyrhynchos: (Corvidae) American crow"
* #COUGAR_(PUMA_CONCOLOR) "Cougar (Puma concolor)"
* #CRAB_PLOVER "Crab plover"
* #CRABS "Crabs"
* #CRANE "Crane"
* #CRAYFISH "Crayfish"
* #CRESTED_GOSHAWK "Crested goshawk"
* #CRESTED_LARK "Crested Lark"
* #CRESTED_MYNA "Crested myna"
* #CROCRODILE_(CROCODILIA) "Crocrodile (Crocodilia)"
* #CROW "Crow"
* #CROWNED_CORMORANT_(MICROCARBO_CORONATUS) "Crowned cormorant (Microcarbo coronatus)"
* #CRUSTACEANS_AMERICAN_AND_EU_LOBSTER_BRINE_SHRIMP "Crustaceans: American And Europeans Lobster, Brine Shrimp"
* #CUERVO "Cuervo"
* #CURLEW "Curlew"
* #DALMATIAN_PELICAN_(PELECANUS_CRISPUS) "Dalmatian pelican (Pelecanus crispus)"
* #DAUBENTON'S_BAT "Daubenton's bat"
* #DEER "Deer"
* #DESERT_COTTONTAIL_(SYLVILAGUS_AUDUBONII) "Desert Cottontail (Sylvilagus audubonii)"
* #DICKINSON'S_KESTREL "Dickinson's kestrel"
* #DOGS "Dogs"
* #DOLPHIN_GULL_(LEUCOPHAEUS_SCORESBII) "Dolphin gull (Leucophaeus scoresbii)"
* #DONKEY "Donkey"
* #DORCAS_GAZELLE "Dorcas Gazelle"
* #DOUBLE_CRESTED_CORMORANT_(NANNOPTERUM_AURITUM) "Double-crested Cormorant (Nannopterum Auritum)"
* #DROMEDARY_(CAMELUS_DROMEDARIUS) "Dromedary (Camelus dromedarius)"
* #DUCK "Duck"
* #EAGLE_OWL_(BUBO_BUBO) "Eagle owl (Bubo bubo)"
* #EARED_GREBE "Eared grebe"
* #EAST_COAST_AKALAT "East coast akalat"
* #EASTERN_BUZZARD_BUTEO_JAPONICUS(ACCIPITRIDAE) "Eastern buzzard:Buteo japonicus(Accipitridae)"
* #EASTERN_COTTONTAIL_SYLVILAGUS_FLORIDANUS "Eastern Cottontail:Sylvilagus floridanus(Leporidae)"
* #EASTERN_GREEN_TINKERBIRD "Eastern green tinkerbird"
* #EASTERN_GREY_KANGAROO_(MACROPUS_GIGANTEUS) "Eastern Grey Kangaroo (Macropus giganteus)"
* #EASTERN_RED_FOOTED_FALCON "Eastern red footed falcon"
* #EGRET "Egret"
* #EGYPTIAN_GOOSE_(ALOPOCHEN_AEGYPTIACUS) "Egyptian Goose (Alopochen aegyptiacus)"
* #ELAND "Eland"
* #ELEPHANT_(AFRICAN_ELEPHANT) "Elephant (African Elephant)"
* #EMU_(DROMAIUS_NOVAEHOLLANDIAE) "Emu (Dromaius novaehollandiae)"
* #EQUIDAE "Equidae"
* #EURASIAN_BLACKBIRD_(TURDUS_MERULA) "Eurasian Blackbird (Turdus merula)"
* #EURASIAN_BUZZARD)_BUTEO_BUTEO "Eurasian buzzard (common buzzard):Buteo buteo(Accipitridae)"
* #EURASIAN_COLLARED_DOVE_(STREPTOPELIA_DECAOCTO) "Eurasian Collared Dove (Streptopelia decaocto)"
* #EURASIAN_COOT_(FULICA_ATRA) "Eurasian coot (Fulica atra)"
* #EURASIAN_EAGLE_OWL_BUBO_BUBO(STRIGIDAE) "Eurasian Eagle-Owl:Bubo bubo(Strigidae)"
* #EURASIAN_OYSTERCATCHER "Eurasian Oystercatcher"
* #EURASIAN_SPARROWHAWK_ACCIPITER_NISUS(ACCIPITRIDAE) "Eurasian Sparrowhawk:Accipiter nisus(Accipitridae)"
* #EURASIAN_SPOONBILL_(PLATALEA_LEUCORODIA) "Eurasian Spoonbill (Platalea leucorodia)"
* #EURASIAN_TREE_SPARROW "Eurasian Tree Sparrow"
* #EURASIAN_WIGEON_ANAS_PENELOPE(ANATIDAE) "Eurasian Wigeon:Anas penelope(Anatidae)"
* #EUROPEAN_PINE_MARTEN "European pine marten"
* #EUROPEAN_RABBIT_(ORYCTOLAGUS_CUNICULUS) "European Rabbit (Oryctolagus cuniculus)"
* #EUROPEAN_TURTLE_DOVE "European turtle dove"
* #FALLOW_DEER_DAMA_DAMA(CERVIDAE) "Fallow Deer:Dama dama(Cervidae)"
* #FERAL_PIG "Feral pig"
* #FERRET "Ferret"
* #FERRET_BADGER "Ferret-badger"
* #FERRUGINOUS_DUCK_(AYTHYA_NYROCA) "Ferruginous Duck (Aythya nyroca)"
* #FISCHER'S_TURACO "Fischer's turaco"
* #FISHER_(PEKANIA_PENNANTI) "Fisher (Pekania pennanti)"
* #FISHING_CAT_(PRIONAILURUS_VIVERRINUS) "Fishing cat (Prionailurus viverrinus)"
* #FOWL "Fowl"
* #FOX "Fox"
* #FRANKLIN'S_GULL "Franklin's Gull"
* #FULVOUS_WHISTLING_DUCK "Fulvous Whistling-Duck"
* #GADWALL "Gadwall"
* #GARGANEY_(ANAS_QUERQUEDULA) "Garganey (Anas querquedula)"
* #GAUR_(BOS_GAURUS) "Gaur (Bos gaurus)"
* #GAYAL_(BOS_FRONTALIS) "Gayal (Bos frontalis)"
* #GIRAFFE "Giraffe"
* #GLOSSY_IBIS "Glossy Ibis"
* #GOAT/SHEEP "Goat/sheep"
* #GOATS "Goats"
* #GOITERED_GAZELLE_(GAZELLA_SUBGUTTUROSA) "Goitered gazelle (Gazella subgutturosa)"
* #GOOSANDER "Goosander"
* #GOOSE "Goose"
* #GORILLA_(GORILLA_GORILLA) "Gorilla (Gorilla gorilla)"
* #GOSHAWK "Goshawk"
* #GRAY_SEAL_(HALICHOERUS_GRYPUS)_PHOCIDAE_CARNIVORA "Gray Seal (Halichoerus grypus):Phocidae-Carnivora"
* #GREAT_BLACK_BACKED_GULL_(LARUS_MARINUS) "Great Black-backed Gull (Larus marinus)"
* #GREAT_BLACK_HEADED_GULL_(ICHTHYAETUS_ICHTHYAETUS) "Great Black-headed Gull (Ichthyaetus ichthyaetus)"
* #GREAT_BLUE_HERON "Great blue heron"
* #GREAT_CORMORANT_(PHALACROCORAX_CARBO) "Great Cormorant (Phalacrocorax carbo)"
* #GREAT_CRESTED_GREBE_(PODICEPS_CRISTATUS) "Great crested grebe (Podiceps cristatus)"
* #GREAT_CRESTED_GREBE_PODICEPS_CRISTATUS "Great Crested Grebe:Podiceps Cristatus(Podicipedidae)"
* #GREAT_EGRET_(ARDEA_ALBA) "Great egret (Ardea alba)"
* #GREAT_HORNED_OWL_(BUBO_VIRGINIANUS) "Great Horned Owl (Bubo Virginianus)"
* #GREAT_MYNA_(ACRIDOTHERES_GRANDIS) "Great Myna (Acridotheres grandis)"
* #GREAT_REED_WARBLER "Great Reed Warbler"
* #GREAT_SNIPE "Great snipe"
* #GREATER_CANE_RAT_OR_GRASSCUTTER "Greater cane rat or Grasscutter (Thryonomys swinderianus)"
* #GREATER_FLAMINGO_(PHOENICOPTERUS_ROSEUS) "Greater flamingo (Phoenicopterus roseus)"
* #GREATER_FRIGATE_BIRD "Greater frigate bird"
* #GREATER_KUDU "Greater Kudu"
* #GREATER_PAINTED_SNIPE "Greater Painted Snipe"
* #GREATER_RHEA_(RHEA_AMERICANA) "Greater Rhea (Rhea americana)"
* #GREATER_SAND_PLOVER "Greater Sand Plover"
* #GREATER_SCAUP "Greater scaup"
* #GREATER_WHITE_FRONTED_GOOSE_(ANSER_ALBIFRONS) "Greater White-fronted Goose (Anser albifrons)"
* #GREATER_YELLOWLEGS "Greater Yellowlegs"
* #GREBE "Grebe"
* #GREEN_BACKED_TWIN_SPOT "Green backed twin spot"
* #GREEN_PIGEON "Green Pigeon"
* #GREEN_SANDPIPER "Green sandpiper"
* #GREEN_WINGED_TEAL/EURASIAN_TEAL "Green-winged teal/Eurasian teal"
* #GREY_CROWNED_CRANE_BALEARICA_REGULORUM(GRUIDAE) "Grey crowned crane:Balearica regulorum(Gruidae)"
* #GREY_GULL(LEUCOPHAEUS_MODESTUS) "Grey gull(Leucophaeus modestus)"
* #GREY_HEADED_GULL_(CHROICOCEPHALUS_CIRROCEPHALUS) "Grey headed gull (Chroicocephalus cirrocephalus)"
* #GREY_HERON_ARDEA_CINEREA(ARDEIDAE) "Grey Heron:Ardea cinerea(Ardeidae)"
* #GREY_PARTRIDGE_PERDIX_PERDIX(PHASIANIDAE) "Grey Partridge:Perdix perdix(Phasianidae)"
* #GREYLAG_GOOSE "Greylag goose"
* #GREYLAG_GOOSE_ANSER_ANSER(ANATIDAE) "Greylag Goose:Anser anser(Anatidae)"
* #GRUIDAE "Gruidae (unidentified):Gruidae (incognita)(Gruidae)"
* #GUANAY_CORMORANT_(LEUCOCARBO_BOUGAINVILLIORUM) "Guanay cormorant (Leucocarbo bougainvilliorum)"
* #GUANAY_CORMORANT_OR_GUANAY_SHAG "Guanay cormorant or Guanay shag (Leucocarbo bougainvilliorum)"
* #GUINEA_FOWL "Guinea fowl"
* #GULL "Gull"
* #HAEMATOPODIDAE "Haematopodidae (unidentified):Haematopodidae (incognita)(Haematopodidae)"
* #HALCÃ³N "HalcÃ³n"
* #HAMSTER_(RODENTIA) "Hamster (Rodentia)"
* #HARBOR_SEAL_(PHOCA_VITULINA)_PHOCIDAE_CARNIVORA "Harbor Seal (Phoca vitulina):Phocidae-Carnivora"
* #HARE "Hare"
* #HARRIS'S_HAWK_(PARABUTEO_UNICINCTUS) "Harris's hawk (Parabuteo unicinctus)"
* #HARTLAUB'S_GULL_(CHROICOCEPHALUS_HARTLAUBII) "Hartlaub's gull (Chroicocephalus hartlaubii)"
* #HAWK "Hawk"
* #HELMETED_GUINEAFOWL_(NUMIDA_MELEAGRIS) "Helmeted guineafowl (Numida meleagris)"
* #HERON "Heron"
* #HERRING_GULL_LARUS_ARGENTATUS(LARIDAE) "Herring Gull:Larus argentatus(Laridae)"
* #HIPPOPOTAMUS "Hippopotamus"
* #HOBBY "Hobby"
* #HOODED_CRANE_GRUS_MONACHA(GRUIDAE) "Hooded crane:Grus monacha(Gruidae)"
* #HOODED_CROW_(CORVUS_CORNIX) "Hooded Crow (Corvus cornix)"
* #HORSE "Horse"
* #HOTTENTOT_TEAL "Hottentot Teal"
* #HOUSE_CROW_(CORVUS_SPLENDENS) "House Crow (Corvus splendens)"
* #HOUSE_SPARROW "House sparrow"
* #HUMBOLDT_PENGUIN_(SPHENISCUS_HUMBOLDTI) "Humboldt penguin (Spheniscus humboldti)"
* #HUMPBACK_WHALE_(MEGAPTERA_NOVAEANGLIAE) "Humpback whale (Megaptera novaeangliae)"
* #IBEX "Ibex"
* #IMPALA "Impala"
* #IMPERIAL_SHAG "Imperial shag"
* #INDIAN_PEAFOWL_(PAVO_CRISTATUS) "Indian Peafowl (Pavo cristatus)"
* #JACKAL "Jackal"
* #JACKAL_BUZZARD_(BUTEO_RUFOFUSCUS) "Jackal buzzard (Buteo rufofuscus)"
* #JACKASS_PENGUIN_SPHENISCUS_DEMERSUS "Jackass Penguin Spheniscus demersus"
* #JACKDAW "Jackdaw"
* #JAGUAR_(PANTHERA_ONCA) "Jaguar (Panthera onca)"
* #JAPANESE_SPARROWHAWK "Japanese sparrowhawk"
* #JAPANESE_WHITE_EYE "Japanese White-eye"
* #KASHMIRI_MARKHOR "Kashmiri Markhor"
* #KELP_GULL "Kelp gull"
* #KENTISH_PLOVER "Kentish plover"
* #KING_CORMORANT "King cormorant"
* #KITE "Kite"
* #KITTLITZ'S_PLOVER "Kittlitz's Plover"
* #KNOB_BILLED_DUCK "Knob-billed Duck"
* #KODIAK_GRIZZLY_BEAR_(URSUS_ARCTOS_HORRIBILIS) "Kodiak grizzly bear (Ursus arctos horribilis)"
* #KUDU "Kudu"
* #LARGE_BILLED_CROW_(CORVUS_MACRORHYNCHOS) "Large-billed Crow (Corvus macrorhynchos)"
* #LARIDAE "Laridae (unidentified):Laridae (incognita)(Laridae)"
* #LAUGHING_DOVE "Laughing dove"
* #LEAST_SANDPIPER "Least Sandpiper"
* #LEOPARD "Leopard"
* #LEPTOPTILOS_CRUMENIFERUS "Leptoptilos crumeniferus"
* #LESSER_BLACK_BACKED_GULL_LARUS_FUSCUS(LARIDAE) "Lesser Black-backed Gull:Larus fuscus(Laridae)"
* #LESSER_CRESTED_TERN "Lesser crested tern"
* #LESSER_FRIGATE_BIRD "Lesser frigate bird"
* #LESSER_SNOW_GOOSE "Lesser Snow Goose"
* #LESSER_WHISTLING_DUCK "Lesser Whistling Duck"
* #LION_(PANTHERA_LEO) "Lion (Panthera leo)"
* #LITTLE_BITTERN "Little Bittern"
* #LITTLE_CORMORANT "Little cormorant"
* #LITTLE_EGRET "Little egret"
* #LITTLE_GREBE "Little Grebe"
* #LITTLE_GREBE_TACHYBAPTUS_RUFICOLLIS(PODICIPEDIDAE) "Little Grebe:Tachybaptus ruficollis(Podicipedidae)"
* #LITTLE_RINGED_PLOVER "Little Ringed Plover"
* #LITTLE_STINT "Little stint"
* #LOBSTER "Lobster"
* #LONG_TOED_LAPWING "Long-toed Lapwing"
* #LORO "loro"
* #MACROBRACHIUM_ROSENBERGII "Macrobrachium rosenbergii"
* #MADAGASCAR_SQUACCO_HERON "Madagascar squacco heron"
* #MAGELLANIC_OYSTERCATCHER_(HAEMATOPUS_LEUCOPODUS) "Magellanic oystercatcher (Haematopus leucopodus)"
* #MAGELLANIC_PENGUIN "Magellanic Penguin"
* #MAGPIE "Magpie"
* #MAINLAND_SEROW_(CAPRICORNIS_SUMATRAENSIS) "Mainland serow (Capricornis sumatraensis)"
* #MALLARD_ANAS_PLATYRHYNCHOS(ANATIDAE) "Mallard:Anas platyrhynchos(Anatidae)"
* #MANDARIN_DUCK_AIX_GALERICULATA(ANATIDAE) "Mandarin Duck:Aix galericulata(Anatidae)"
* #MANED_DUCK_CHENONETTA_JUBATA(ANATIDAE) "Maned Duck:Chenonetta jubata(Anatidae)"
* #MARABOU_STORK "Marabou Stork"
* #MARBLED_TEAL "Marbled teal"
* #MARSH_HARRIER "Marsh Harrier"
* #MASCARENE_MARTIN "Mascarene martin"
* #MASKED_BOOBY "Masked booby"
* #MEDITERRANEAN_GULL "Mediterranean Gull"
* #MEW_GULL_(LARUS_CANUS) "Mew gull (Larus canus)"
* #MILK_FISH/CHONOS_CHONOS "Milk fish/Chonos chonos"
* #MINK "Mink"
* #MONGOLIAN_SAIGA_(SAIGA_TATARICA_MONGOLICA) "Mongolian saiga (Saiga tatarica mongolica)"
* #MONKEY "Monkey"
* #MOOSE_(ALCES_ALCES) "Moose (Alces alces)"
* #MOTACILLIDAE "Motacillidae (unidentified):Motacillidae (incognita)(Motacillidae)"
* #MOUFLON_(OVIS_ORIENTALIS) "Mouflon (Ovis orientalis)"
* #MOUNTAIN_HARE_(LEPUS_TIMIDUS) "Mountain hare (Lepus timidus)"
* #MOUNTAIN_HAWK_EAGLE "Mountain Hawk-Eagle"
* #MOUSE_COLOURED_SUNBIRD "Mouse coloured sunbird"
* #MUD_CRABS/SCYLLA_CERATTA "Mud crabs/Scylla ceratta"
* #MULE_(EQUUS_MULUS) "Mule (Equus mulus)"
* #MULE_DEER_(ODOCOILEUS_HEMIONUS) "Mule deer  (Odocoileus hemionus)"
* #MUSCOVY_DUCK_CAIRINA_MOSCHATA(ANATIDAE) "Muscovy Duck:Cairina moschata(Anatidae)"
* #MUTE_SWAN_CYGNUS_OLOR(ANATIDAE) "Mute Swan:Cygnus olor(Anatidae)"
* #MYNAHS "Mynahs"
* #NAMAQUA_DOVE "Namaqua Dove"
* #NORTHERN_GANNET_MORUS_BASSANUS(SULIDAE) "Northern Gannet:Morus bassanus(Sulidae)"
* #NORTHERN_LAPWING "Northern Lapwing"
* #NORTHERN_PINTAIL_(ANAS_ACUTA) "Northern pintail (Anas acuta)"
* #NORTHERN_SHOVELER "Northern shoveler"
* #NUMIDIDAE_(UNIDENTIFIED) "Numididae (Unidentified)"
* #NYALA_(TRAGELAPHUS_ANGASII) "Nyala (Tragelaphus angasii)"
* #OLROG'S_GULL "Olrog's Gull"
* #OPEN_BILLED_STORKS "Open-billed storks"
* #ORANGE_BISHOP "Orange Bishop"
* #ORANGE_WINGED_PYTILIA "Orange winged pytilia"
* #ORANGE_CHEEKED_WAXBILL "Orange-cheeked Waxbill"
* #ORANGUTAN "Orangutan"
* #ORIENTAL_MAGPIE_ROBIN "Oriental Magpie Robin"
* #OSPREY "Osprey"
* #OSTRICH "Ostrich"
* #OTTER_(LUTRINAE) "Otter (Lutrinae)"
* #OWL "Owl"
* #OYSTER_CATCHER "Oyster catcher"
* #OYSTERS "Oysters"
* #PACIFIC_LOON_(GAVIA_PACIFICA) "Pacific loon (Gavia pacifica)"
* #PALE_BREASTED_ILLADOPSIS "Pale-breasted illadopsis"
* #PANGOLIN_(MANIS) "Pangolin  (Manis)"
* #PARROT "Parrot"
* #PARTRIDGE "Partridge"
* #PASSERIDAE "Passeridae (unidentified):Passeridae (incognita)(Passeridae)"
* #PATAGONIAN_MARA_(DOLICHOTIS_PATAGONUM) "Patagonian mara (Dolichotis patagonum)"
* #PAVO_REAL "Pavo real"
* #PEACOCK "Peacock"
* #PECTORAL_SANDPIPER "Pectoral sandpiper"
* #PELECANIDAE "Pelecanidae (unidentified):Pelecanidae (incognita)(Pelecanidae)"
* #PEMBA_FLYING_FOX "Pemba flying fox"
* #PEMBA_GREEN_PIGEON "Pemba green pigeon"
* #PEMBA_SCOPS_OWL "Pemba scops owl"
* #PEMBA_VIOLET_BREASTED_SUNBIRD "Pemba violet breasted sunbird"
* #PEMBA_WHITE_EYE "Pemba white eye"
* #PENGUIN "Penguin"
* #PEREGRIN_FALCON_FALCO_PEREGRINUS(FALCONIDAE) "Peregrin falcon:Falco peregrinus(Falconidae)"
* #PERUVIAN_OR_ANDEAN_GULL_(CHROICOCEPHALUS_SERRANUS) "Peruvian or Andean gull (Chroicocephalus serranus)"
* #PHALAROPES "Phalaropes"
* #PHASIANIDAE "Phasianidae (unidentified):Phasianidae (incognita)(Phasianidae)"
* #PHASIANUS_COLCHICUS_(COMMON_PHEASANT)__PHASANIDAE "Phasianus colchicus (Common pheasant) - Phasanidae"
* #PHEASANT_TAILED_JACANA "Pheasant-tailed Jacana"
* #PHILIPPINE_COLUGO_(CYNOCEPHALUS_VOLANS) "Philippine colugo (Cynocephalus volans)"
* #PHOENICOPTERIDAE "Phoenicopteridae (unidentified):Phoenicopteridae (incognita)(Phoenicopteridae)"
* #PIED_AVOCET "Pied avocet"
* #PIED_CROW_(CORVUS_ALBUS) "Pied crow (Corvus albus)"
* #PIED_KINGFISHER "Pied Kingfisher"
* #PIED_MANNIKIN "Pied mannikin"
* #PIGEON "Pigeon"
* #PLAIN_BACKED_SPARROW "Plain-backed Sparrow"
* #PLUMED_WHISTLING_DUCK_DENDROCYGNA_EYTONI(ANATIDAE) "Plumed Whistling-Duck:Dendrocygna eytoni(Anatidae)"
* #POCHARD "Pochard"
* #POLAR_FOX "Polar fox"
* #POLECAT "Polecat"
* #POMARINE_SKUA_(OR_POMARINE_JAEGER) "Pomarine skua (or pomarine jaeger)"
* #PONY "Pony"
* #PRAWN "Prawn"
* #PURPLE_GALLINULE "Purple gallinule"
* #PURPLE_SWAMPHEN "Purple Swamphen"
* #PYGMY_GOOSE "Pygmy goose"
* #RABBITS "Rabbits"
* #RAZORBILL_ALCA_TORDA "Razorbill (Alca torda):Alcidae-Charadriiformes"
* #RED_AVADAVAT "Red Avadavat"
* #RED_BREASTED_GOOSE "Red breasted goose"
* #RED_CHESTED_CRAKE "Red chested crake"
* #RED_COLOBUS_MONKEY "Red colobus monkey"
* #RED_CRESTED_POCHARD_(NETTA_RUFINA) "Red crested pochard (Netta rufina)"
* #RED_FOX "Red Fox"
* #RED_JUNGLEFOWL "Red junglefowl"
* #RED_KNOT "Red Knot"
* #RED_SHOVELER "Red shoveler"
* #RED_TURTLE_DOVE "Red turtle dove"
* #RED_AND_GREEN_MACAW_(ARA_CHLOROPTERUS) "Red-and-green macaw (Ara chloropterus)"
* #RED_BILLED_FIREFINCH "Red-billed Firefinch"
* #RED_BILLED_QUELEA "Red-billed Quelea"
* #RED_BILLED_STARLING "Red-billed Starling"
* #RED_BILLED_TEAL "Red-Billed Teal"
* #RED_CHEEKED_CORDON_BLEU "Red-cheeked Cordon-bleu"
* #RED_CROWNED_CRANE_(GRUS_JAPONENSIS) "Red-crowned crane (Grus japonensis)"
* #RED_HEADED_VULTURE_(SARCOGYPS_CALVUS) "Red-headed vulture (Sarcogyps calvus)"
* #RED_KNOBBED_COOT "Red-knobbed Coot"
* #RED_TAILED_HAWK "Red-tailed hawk"
* #RED_WATTLED_LAPWING "Red-wattled lapwing"
* #REED_BUNTING "Reed Bunting"
* #REED_CORMORANT "Reed Cormorant"
* #RING_NECKED_DUCK "Ring Necked Duck"
* #RING_BILLED_GULL_(LARUS_DELAWARENSIS) "Ring-billed gull (Larus delawarensis)"
* #ROCK_DOVE "Rock dove"
* #RODENTS "Rodents"
* #ROE_DEER "Roe deer"
* #ROOK "Rook"
* #ROSE_PELICAN_(PELECANUS_ONOCROTALUS) "Rose Pelican (Pelecanus onocrotalus)"
* #ROSS'S_GOOSE_(ANSER_ROSSII) "Ross's goose (Anser rossii)"
* #ROSY_BILLED_POCHARD "Rosy-billed Pochard"
* #ROUGH_LEGGED_HAWK "Rough-legged Hawk"
* #ROYAL_TERN "Royal tern"
* #RUDDY_SHELDUCK "Ruddy shelduck"
* #RUDDY_BREASTED_CRAKE "Ruddy-breasted Crake"
* #RUFF "Ruff"
* #RUMINANTS "Ruminants"
* #SALMON "Salmon"
* #SALMONIDAE "Salmonidae"
* #SAMBAR_(CERVUS_UNICOLOR) "Sambar (Cervus unicolor)"
* #SANDERLING "Sanderling"
* #SANDWICH_TERN "Sandwich tern"
* #SARI "Sari"
* #SCALLOPS_AND_OYSTERS "Scallops And Oysters"
* #SCALY_BREASTED_MUNIA "Scaly-breasted Munia"
* #SCOLOPACIDAE "Scolopacidae (unidentified):Scolopacidae (incognita)(Scolopacidae)"
* #SEA_CUCUMBER/TROPICAL_SPECIES "Sea cucumber/Tropical species"
* #SEA_LION "Sea lion"
* #SECRETARY_BIRD_(SAGITTARIUS_SERPENTARIUS) "Secretary bird (Sagittarius serpentarius)"
* #SEMIPALMATED_PLOVER "Semipalmated Plover"
* #SEMIPALMATED_SANDPIPER "Semipalmated Sandpiper"
* #SERVAL_(LEPTAILURUS_SERVAL) "Serval (Leptailurus serval)"
* #SHAMA_ORIENTAL "Shama oriental"
* #SHEEP "Sheep"
* #SHIKRA "Shikra"
* #SHRIMP "Shrimp"
* #SILVER_TEAL_(ANAS_VERSICOLOR) "Silver Teal (Anas versicolor)"
* #SKUNK "Skunk"
* #SLATY_BREASTED_RAIL "Slaty-breasted Rail"
* #SLENDER_BILLED_GULL "Slender-billed Gull"
* #SMALL_RUMINANT "Small Ruminant"
* #SNAKES "Snakes"
* #SNOW_GOOSE_(ANSER_CAERULESCENS) "Snow goose (Anser caerulescens)"
* #SNOW_LEOPARD_(PANTHERA_UNCIA) "Snow leopard (Panthera uncia)"
* #SNOWY_OWL_(BUBO_SCANDIACUS) "Snowy Owl (Bubo scandiacus)"
* #SOUTH_AMERICAN_SEA_LION_(OTARIA_FLAVESCENS) "South American sea lion (Otaria flavescens)"
* #SOUTH_AMERICAN_TERN "South American Tern"
* #SOUTHERN_LAPWING "Southern Lapwing"
* #SPECKLED_TEAL "Speckled Teal"
* #SPOT_BILLED_DUCK_ANAS_POECILORHYNCHA(ANATIDAE) "Spot-billed Duck:Anas poecilorhyncha(Anatidae)"
* #SPOTTED_CRAKE "Spotted crake"
* #SPOTTED_DOVE "Spotted dove"
* #SPOTTED_EAGLE_OWL_(BUBO_AFRICANUS) "Spotted eagle-owl (Bubo africanus)"
* #SPOTTED_HYENA_(CROCUTA_CROCUTA) "Spotted hyena (Crocuta crocuta)"
* #SPOTTED_SANDPIPER "Spotted sandpiper"
* #SPOTTED_WOOD_OWL_(STRIX_SELOPUTO) "Spotted wood owl (Strix seloputo)"
* #SPRINGBOK "Springbok"
* #SPUR_WINGED_GOOSE "Spur-winged Goose"
* #SPUR_WINGED_LAPWING "Spur-winged Lapwing"
* #STARLING "Starling"
* #STONE_MARTEN "Stone marten"
* #STORK "Stork"
* #STREAK_EARED_BULBUL "Streak-eared Bulbul"
* #STREAKED_WEAVER "Streaked Weaver"
* #STRIGIDAE "Strigidae (unidentified):Strigidae (incognita)(Strigidae)"
* #STRIPED_CRAKE "Striped crake"
* #SUNCUS_MURINUS "Suncus murinus"
* #SWAINSON'S_HAWK "Swainson's Hawk"
* #SWALLOW "Swallow"
* #SWAN "Swan"
* #SWIFT_TERN_(THALASSEUS_BERGII) "Swift tern (Thalasseus bergii)"
* #SWINE "Swine"
* #SYDNEY_ROCK_OYSTER_SACCOSTREA_GLOMERATA "Sydney Rock Oyster Saccostrea Glomerata"
* #TAIWAN_BLUE_MAGPIE "Taiwan Blue Magpie"
* #TEAL "Teal"
* #TEREK_SANDPIPER "Terek sandpiper"
* #TERN "Tern"
* #TETRAONINAE "Tetraoninae (unidentified):Tetraoninae (incognita)(Phasianidae)"
* #THE_GIANT_FRESHWATER_PRAWN "The Giant Freshwater Prawn"
* #THICK_BILLED_WARBLER "Thick-billed Warbler"
* #THRESKIORNITHIDAE "Threskiornithidae (unidentified):Threskiornithidae (incognita)(Threskiornithidae)"
* #THRUSH_(TURDIDAE) "Thrush (Turdidae)"
* #TIGER_(PANTHERA_TIGRIS) "Tiger (Panthera tigris)"
* #TRUMPETER_SWAN_(CYGNUS_BUCCINATOR) "Trumpeter swan (Cygnus buccinator)"
* #TUFTED_DUCK "Tufted duck"
* #TUNDRA_SWAN "Tundra swan"
* #TURKEY "Turkey"
* #TURKEY_VULTURE_(CATHARTES_AURA) "Turkey vulture (Cathartes aura)"
* #TURTLEDOVE "Turtledove"
* #UMBRELLA_COCKATOO "Umbrella cockatoo"
* #UNSPECIFIED_AMPHIBIANS "Unspecified Amphibians"
* #UNSPECIFIED_ARTHROPOD "Unspecified arthropod"
* #UNSPECIFIED_BIRD "Unspecified bird"
* #UNSPECIFIED_CRUSTACEANS "Unspecified Crustaceans"
* #UNSPECIFIED_ENV_SAMPLE "Unspecified env. sample"
* #UNSPECIFIED_FISH "Unspecified fish"
* #UNSPECIFIED_MAMMAL "Unspecified mammal"
* #UNSPECIFIED_MOLLUSK "Unspecified Mollusk"
* #UNSPECIFIED_REPTILES "Unspecified Reptiles"
* #URAL_OWL "Ural owl"
* #VIOLET_TIPPED_COURSER_(OR_BRONZE_WINGED_COURSER) "Violet tipped courser (or bronze-winged courser)"
* #VULTURE "Vulture"
* #WADER "Wader"
* #WARBLER "Warbler"
* #WARTHOG "Warthog"
* #WATER_BUFFALO "Water buffalo"
* #WATER_HEN "Water hen"
* #WATERCOCK "Watercock"
* #WESTERN_GREBE_(AECHMOPHORUS_OCCIDENTALIS) "Western Grebe (Aechmophorus occidentalis)"
* #WHISKERED_TERN "Whiskered tern"
* #WHITE_BACKED_DUCK "White backed duck"
* #WHITE_BACKED_NIGHT_HERON "White backed night heron"
* #WHITE_FRONTED_SAND_PLOVER "White fronted sand plover"
* #WHITE_RHINOCEROS_(CERATOTHERIUM_SIMUM) "White rhinoceros (Ceratotherium simum)"
* #WHITE_STORK_CICONIA_CICONIA(CICONIIDAE) "White Stork:Ciconia ciconia(Ciconiidae)"
* #WHITE_TAILED_EAGLE_(HALIAEETUS_ALBICILLA) "White tailed eagle (Haliaeetus albicilla)"
* #WHITE_BREASTED_WATERHEN "White-breasted Waterhen"
* #WHITE_CHEEKED_PINTAIL "White-cheeked pintail"
* #WHITE_FACED_WHISTLING_DUCK "White-faced Whistling-Duck"
* #WHITE_NAPED_CRANE_GRUS_VIPIO(GRUIDAE) "White-naped crane:Grus vipio(Gruidae)"
* #WHITE_RUMPED_MUNIA "White-rumped Munia"
* #WHITE_RUMPED_SANDPIPER "White-rumped Sandpiper"
* #WHITE_TAILED_DEER_(ODOCOILEUS_VIRGINIANUS) "White-tailed deer (Odocoileus virginianus)"
* #WHITE_WINGED_BLACK_TERN_(CHLIDONIAS_LEUCOPTERUS) "White-winged black tern (Chlidonias leucopterus)"
* #WHITE_WINGED_COOT "White-winged Coot"
* #WHOOPER_SWAN_CYGNUS_CYGNUS(ANATIDAE) "Whooper Swan:Cygnus cygnus(Anatidae)"
* #WIGEONS_MARECA_PENELOPE(ANATIDAE) "Wigeons:Mareca penelope(Anatidae)"
* #WILD_BOAR_SUS_SCROFA(SUIDAE) "Wild boar:Sus scrofa(Suidae)"
* #WILD_CAT "Wild cat"
* #WILD_DOG "Wild dog"
* #WILD_DUCK "Wild duck"
* #WILD_FOX "Wild fox"
* #WILD_GOAT "Wild goat"
* #WILD_HORSE "Wild horse"
* #WILD_RABBIT "Wild rabbit"
* #WILD_REINDEER "Wild reindeer"
* #WILD_TUNDRA_SWAN "Wild tundra swan"
* #WILD_TURKEY_(MELEAGRIS_GALLOPAVO) "Wild turkey (Meleagris gallopavo)"
* #WILD_WATERFOWL_(WILD_DUCKS) "Wild waterfowl (wild ducks)"
* #WOLF "Wolf"
* #WOOD_DUCK_(AIX_SPONSA)_(ANATIDAE) "Wood Duck (Aix sponsa) (Anatidae)"
* #WOOD_SANDPIPER "Wood sandpiper"
* #WOOD_WARBLER "Wood warbler"
* #YAKS "Yaks"
* #YELLOW_BILLED_DUCK_(ANAS_UNDULATA) "Yellow-billed duck (Anas undulata)"
* #YELLOW_HOODED_BLACKBIRD "Yellow-hooded Blackbird"
* #YELLOW_LEGGED_GULL "Yellow-legged Gull"
* #YELLOW_THROATED_MARTEN_(MARTES_FLAVIGULA) "Yellow-throated marten (Martes flavigula)"
* #YELLOW_VENTED_BULBUL "Yellow-vented Bulbul"
* #ZANZIBAR_BUSHY_TAILED_MONGOOSE "Zanzibar bushy tailed mongoose"
* #ZANZIBAR_FOUR_TOTHEDED_ELEPHANT_SHREW "Zanzibar four totheded elephant shrew"
* #ZANZIBAR_PYGMY_SHREW "Zanzibar pygmy shrew"
* #ZANZIBAR_SLENDER_MONGOOSE "Zanzibar slender mongoose"
* #ZEBRAS "Zebras"
* #ABERT'S_SQUIRREL_SCIURUS_ABERTI "Abert's squirrel (Sciurus aberti)"
* #AMERICAN_BLACK_BEAR_URSUS_AMERICANUS "American black bear (Ursus americanus)"
* #AMUR_LEOPARD_PANTHERA_PARDUS_ORIENTALIS "Amur leopard (Panthera pardus orientalis)"
* #ANDEAN_GOOSE_CHLOEPHAGA_MELANOPTERA "Andean goose (Chloephaga melanoptera)"
* #ANSER_BRACHYRHYNCHUS_PINK_FOOTED_GOOSE__ANATIDAE "Anser brachyrhynchus (Pink footed goose) - Anatidae"
* #ANTARCTIC_PRION_PACHYPTILA_DESOLATA "Antarctic prion (Pachyptila desolata)"
* #ARGALI_OVIS_AMMON "Argali (Ovis ammon)"
* #ATLANTIC_PUFFIN_FRATERCULA_ARCTICA "Atlantic puffin (Fratercula arctica)"
* #BEARDED_VULTURE_GYPAETUS_BARBATUS "Bearded vulture (Gypaetus barbatus)"
* #BIG_HAIRY_ARMADILLOS_CHAETOPHRACTUS_VILLOSUS "Big hairy armadillos (Chaetophractus villosus)"
* #BLACK_AND_WHITE_RUFFED_LEMUR_VARECIA_VARIEGATA "Black-and-white ruffed lemur (Varecia variegata)"
* #CORVIDAE_PASSERIFORMES "Black-billed Magpie (Pica hudsonia):Corvidae-Passeriformes"
* #BLACK_BROWED_ALBATROSS_THALASSARCHE_MELANOPHRIS "Black-browed albatross (Thalassarche melanophris)"
* #ALCIDAE_CHARADRIIFORMES "Black Guillemot (Cepphus grylle):Alcidae-Charadriiformes"
* #PODICIPEDIDAE_PROCELLARIIFORMES "Black-necked Grebe (Podiceps nigricollis):Podicipedidae-Procellariiformes"
* #BLACK_STORK_CICONIA_NIGRA "Black stork (Ciconia nigra)"
* #BLACK_TAILED_MARMOSET_MICO_MELANURUS "Black-tailed marmoset (Mico melanurus)"
* #BLUE_AND_WHITE_SWALLOW_PYGOCHELIDON_CYANOLEUCA "Blue-and-white swallow (Pygochelidon cyanoleuca)"
* #BLUE_FOOTED_BOOBY_SULA_NEBOUXII "Blue-footed booby (Sula nebouxii)"
* #BLUE_FRONTED_AMAZON_AMAZONA_AESTIVA "Blue-fronted amazon (Amazona aestiva)"
* #ANATIDAE_ANSERIFORMES "Blue winged teal (Anas discors):Anatidae-Anseriformes"
* #BOBCAT_LYNX_RUFUS "Bobcat (Lynx rufus)"
* #BORNEAN_BINTURONG_ARCTICTIS_BINTURONG "Bornean binturong (Arctictis binturong)"
* #BOTTLENOSE_DOLPHIN_TURSIOPS_TRUNCATUS "Bottlenose dolphin (Tursiops truncatus)"
* #BROWN_BOOBY_SULA_LEUCOGASTER "Brown Booby (Sula leucogaster)"
* #BROWN_SKUA_STERCORARIUS_ANTARCTICUS "Brown skua (Stercorarius antarcticus)"
* #BUBO_SCANDIACUS_SNOWY_OWL__STRIGIDAE "Bubo scandiacus (Snowy Owl) - Strigidae"
* #BUCEPHALA_ALBEOLA_ANSERIFORMES_BUFFLEHEAD "Bucephala albeola: (Anseriformes) Bufflehead"
* #BURMEISTER'S_PORPOISE_PHOCOENA_SPINIPINNIS "Burmeister's porpoise (Phocoena spinipinnis)"
* #BUTEO_JAMAICENSIS_RED_TAILED_HAWK__ACCIPITRIDAE "Buteo jamaicensis (Red-tailed hawk ) - Accipitridae"
* #CABOT'S_TERN_THALASSEUS_ACUFLAVIDUS "Cabot's tern (Thalasseus acuflavidus)"
* #CACKLING_GOOSE_BRANTA_HUTCHINSII "Cackling goose (Branta hutchinsii)"
* #CASPIAN_GULL_LARUS_CACHINNANS "Caspian gull (Larus cachinnans)"
* #CASPIAN_TERN_HYDROPROGNE_CASPIA "Caspian tern (Hydroprogne caspia)"
* #CHILEAN_DOLPHIN_CEPHALORHYNCHUS_EUTROPIA "Chilean dolphin (Cephalorhynchus eutropia)"
* #CHILEAN_FLAMINGO_PHOENICOPTERUS_CHILENSIS "Chilean flamingo (Phoenicopterus chilensis)"
* #CHLORIS_CHLORIS_FRINGILLIDAE_EUROPEAN_GREENFINCH "Chloris chloris: (Fringillidae) European greenfinch"
* #CHROICOCEPHALUS_RIDIBUNDUS_BLACK_HEADED_GULL "Chroicocephalus ridibundus : (Black headed gull)"
* #COMMON_RACCOON_PROCYON_LOTOR "Common raccoon (Procyon lotor)"
* #COOPER'S_HAWK_ACCIPITER_COOPERII "Cooper's hawk (Accipiter cooperii)"
* #CORVIDAE_INCOGNITA "Corvidae (incognita)"
* #COYOTE_CANIS_LATRANS "Coyote (Canis latrans)"
* #CRESTED_SERPENT_EAGLE_SPILORNIS_CHEELA "Crested serpent eagle (Spilornis cheela)"
* #DAUBETON'S_BAT "Daubeton's bat"
* #EURASIAN_JACKDAW_COLOEUS_MONEDULA "Eurasian jackdaw (Coloeus monedula)"
* #GIANT_ANTEATER_MYRMECOPHAGA_TRIDACTYLA "Giant anteater (Myrmecophaga tridactyla)"
* #GLAUCOUS_GULL_LARUS_HYPERBOREUS "Glaucous gull (Larus hyperboreus)"
* #GRAY_HAWK_BUTEO_PLAGIATUS "Gray hawk (Buteo plagiatus)"
* #GREATER_CANE_RAT "Greater cane rat"
* #GREAT_SKUA_STERCORARIUS_SKUA "Great skua (Stercorarius skua)"
* #ICTERIDAE_PELECANIFORMES "Great-tailed Grackle (Quiscalus mexicanus):Icteridae-Pelecaniformes"
* #GRIFFON_VULTURE_GYPS_FULVUS "Griffon vulture (Gyps fulvus)"
* #GUINEA_PIGS "Guinea pigs"
* #GULL_BILLED_TERN_GELOCHELIDON_NILOTICA "Gull-billed tern (Gelochelidon nilotica)"
* #HALIAEETUS_PELAGICUS_STELLER'S_SEA_EAGLE "Haliaeetus pelagicus (Steller's sea eagle)"
* #ICELAND_GULL_LARUS_GLAUCOIDES "Iceland gull (Larus glaucoides)"
* #ACCIPITRIDAE_ACCIPITRIFORMES "Imperial Eagle (Aquila heliaca):Accipitridae-Accipitriformes"
* #IVORY_GULL_PAGOPHILA_EBURNEA "Ivory gull (Pagophila eburnea)"
* #LESSER_SAND_PLOVER_CHARADRIUS_MONGOLUS "Lesser sand plover (Charadrius mongolus)"
* #LITTLE_OWL_ATHENE_NOCTUA_STRIGIDAE_SULIFORMES "Little Owl (Athene noctua):Strigidae-Suliformes"
* #MAGNIFICENT_FRIGATEBIRD_FREGATA_MAGNIFICENS "Magnificent frigatebird (Fregata magnificens)"
* #MANDRILLUS_SPHINX_MANDRILL "Mandrillus sphinx Mandrill"
* #MANX_SHEARWATER_PUFFINUS_PUFFINUS "Manx shearwater (Puffinus puffinus)"
* #MARINE_OTTER_LONTRA_FELINA "Marine otter (Lontra felina)"
* #MERGUS_SERRATOR_ANATIDAE_RED_BREASTED_MERGANSER "Mergus serrator: (Anatidae) Red-breasted merganser"
* #MERLIN_FALCO_COLUMBARIUS "Merlin (Falco columbarius)"
* #MONKEY_SQUIRREL_SAIMIRI_SCIUREUS "Monkey squirrel (Saimiri sciureus)"
* #NEOTROPIC_CORMORANT_NANNOPTERUM_BRASILIANUM "Neotropic cormorant (Nannopterum brasilianum)"
* #NORTHERN_BALD_IBIS_GERONTICUS_EREMITA "Northern bald ibis (Geronticus eremita)"
* #NORTHERN_CRESTED_CARACARA_CARACARA_CHERIWAY "Northern crested caracara (Caracara cheriway)"
* #NORTHERN_FULMAR_FULMARUS_GLACIALIS "Northern fulmar (Fulmarus glacialis)"
* #NYCTEREUTES_VIVERRINUS_JAPANESE_RACOON_DOG "Nyctereutes viverrinus (Japanese Racoon Dog)"
* #PALLAS'S_GULL_ICHTHYAETUS_ICHTHYAETUS "Pallas's gull (Ichthyaetus ichthyaetus)"
* #PALLID_HARRIER "Pallid harrier"
* #PERUVIAN_BOOBY_SULA_VARIEGATA "Peruvian Booby (Sula variegata)"
* #PERUVIAN_PELICAN_PELECANUS_THAGUS "Peruvian pelican (Pelecanus thagus)"
* #PINK_FOOTED_GOOSE_ANSER_BRACHYRHYNCHUS "Pink-footed Goose (Anser brachyrhynchus)"
* #PINTAIL_DUCK_ANAS_ACUTA "Pintail duck (Anas acuta)"
* #PODICIPEDIDAE_INCOGNITA "Podicipedidae (incognita)"
* #POLAR_BEAR_URSUS_MARITIMUS "Polar bear (Ursus maritimus)"
* #PURPLE_SANDPIPER_CALIDRIS_MARITIMA "Purple sandpiper (Calidris maritima)"
* #LARIDAE_CHARADRIIFORMES "Red-billed Gull (Larus scopulinus):Laridae-Charadriiformes"
* #RED_BREASTED_MERGANSER_MERGUS_SERRATOR "Red-breasted merganser (Mergus serrator)"
* #RED_FOOTED_BOOBY_SULA_SULA "Red-footed Booby (Sula sula)"
* #RED_GARTERED_COOT_FULICA_ARMILLATA "Red-gartered coot (Fulica armillata)"
* #RED_SHOULDERED_HAWK_BUTEO_LINEATUS "Red-shouldered hawk (Buteo lineatus)"
* #RED_TAILED_HAWK_BUTEO_JAMAICENSIS "Red-tailed hawk (Buteo jamaicensis)"
* #ROCK_DOVE_COLUMBA_LIVIA "Rock dove (Columba livia)"
* #SABLE_MARTES_ZIBELLINA "Sable (Martes zibellina)"
* #SAKER_FALCON_FALCO_CHERRUG "Saker falcon (Falco cherrug)"
* #SEA_OTTER_ENHYDRA_LUTRIS "Sea otter (Enhydra lutris)"
* #SKUNK_MEPHITIS_MEPHITIS "Skunk (Mephitis mephitis)"
* #SOUTH_AMERICA_FUR_SEAL_ARCTOPHOCA_AUSTRALIS "South America fur seal (Arctophoca australis)"
* #PROCYONIDAE_CARNIVORA "South American Coati (Nasua nasua):Procyonidae-Carnivora"
* #SOUTHERN_ELEPHANT_SEAL_M._LEONINA "Southern elephant seal (M. leonina)"
* #SOUTHERN_RIVER_OTTER_LONTRA_PROVOCAX "Southern river otter (Lontra provocax)"
* #SOUTHERN_FULMAR_FULMARUS_GLACIALOIDES "Southern fulmar (Fulmarus Glacialoides)"
* #SPOTTED_SHAG_PHALACROCORAX_PUNCTATUS "Spotted shag (Phalacrocorax punctatus)"
* #STELLER'S_SEA_EAGLE_HALIAEETUS_PELAGICUS "Steller's sea eagle (Haliaeetus pelagicus)"
* #SULIDS_SULIDAE "Sulids (Sulidae)"
* #MELANITTA_PERSPICILLATA "Surf Scoter (Melanitta perspicillata):Anatidae-Anseriformes"
* #SWAINSON'S_HAWK_BUTEO_SWAINSONI "Swainson's hawk (Buteo swainsoni)"
* #TAWNY_OWL_STRIX_ALUCO "Tawny owl (Strix aluco)"
* #URIA_LOMVIA "Thick-billed Murre (Uria lomvia):Alcidae-Charadriiformes"
* #TUNDRA_SWAN_CYGNUS_COLUMBIANUS "Tundra swan (Cygnus columbianus)"
* #VARIABLE_HAWK_GERANOAETUS_POLYOSOMA "Variable hawk (Geranoaetus polyosoma)"
* #VIRGINIA_OPOSSUM_DIDELPHIS_VIRGINIANA "Virginia opossum (Didelphis virginiana)"
