CodeSystem: DiseasesCS
Id: diseases-cs
Title: "Diseases Code System"
Description: "Code system for diseases."

* #ABALONE_HERPES "Abalone Herpes"
* #ACARAPISOSIS_OF_HONEY_BEES "Acarapisosis of honey bees"
* #AFRICAN_HORSE_SICKNESS "African horse sickness"
* #AFRICAN_SWINE_FEVER "African swine fever"
* #AKABANE_DISEASE "Akabane Disease"
* #ALASKAPOX_VIRUS "Alaskapox virus"
* #ALGAL_BLOOM_OF_MICRCYSTICS "Algal bloom of micrcystics"
* #AMERICAN_FOULBROOD_OF_HONEY_BEES "American foulbrood of honey bees"
* #AMYLOODINIUM_SPP_INFECTION "Amyloodinium spp infection"
* #ANAPLASMA_SPP "Anaplasma spp"
* #ANTHRAX "Anthrax"
* #ARENA_VIRUS "Arena virus"
* #ARGENTINE_HEMORRHAGIC_FEVER_JUNIN_VIRUS "Argentine hemorrhagic fever (Junin virus)"
* #ASPERGILLOSIS "Aspergillosis"
* #ATKINSIELLA_SPP "Atkinsiella spp"
* #ATRESIA_ANI "Atresia Ani"
* #ATROPHIC_RHINITIS_AR "Atrophic Rhinitis (AR)"
* #AUJESZKY'S_DISEASE "Aujeszky's disease"
* #AVIAN_CHLAMYDIOSIS "Avian chlamydiosis"
* #AVIAN_INFECTIOUS_BRONCHITIS "Avian infectious bronchitis"
* #AVIAN_INFECTIOUS_LARYNGOTRACHEITIS "Avian infectious laryngotracheitis"
* #AVIAN_MYCOPLASMOSIS_M_GALLISEPTICUM "Avian mycoplasmosis (M. gallisepticum)"
* #AVIAN_MYCOPLASMOSIS_M_SYNOVIAE "Avian mycoplasmosis (M. synoviae)"
* #AVIAN_MYCOPLASMOSIS_M_SYNSHEEPAE "Avian mycoplasmosis (M. synsheepae)"
* #AVIAN_TUBERCULOSIS "Avian tuberculosis"
* #BABESIA_SPP "Babesia spp"
* #BACTERIAL_ENTERIC_DISEASES "Bacterial Enteric Diseases"
* #BACTERIAL_KIDNEY_DISEASE "Bacterial kidney disease (Renibacterium salmoninarum)"
* #BACTERIAL_MENINGITIS "Bacterial Meningitis"
* #NECROSIS_SHELL_DISEASE_FILAMENTOUS_BACTERIAL "Bactrial necrosis/shell disease Filamentous bacterial diseases"
* #BACULOVIRUS_INFECTION "Baculovirus infection"
* #BATRACHOCHYTRIUM_DENDROBATIDIS "Batrachochytrium dendrobatidis"
* #BEETLES "Beetles"
* #BLACK_DISEASE "Black disease"
* #BLACKLEG "Blackleg"
* #BLUETONGUE "Bluetongue"
* #BONAMIA_EXITIOSA "Bonamia exitiosa"
* #BONAMIA_OSTREAE "Bonamia ostreae"
* #BOTULISM "Botulism"
* #BOVINE_ANAPLASMOSIS "Bovine anaplasmosis"
* #BOVINE_BABESIOSIS "Bovine babesiosis"
* #BOVINE_CYSTICERCOSIS "Bovine cysticercosis"
* #BOVINE_GENITAL_CAMPYLOBACTERIOSIS "Bovine genital campylobacteriosis"
* #BOVINE_SPONGIFORM_ENCEPHALOPATHY "Bovine spongiform encephalopathy"
* #BOVINE_TUBERCULOSIS "Bovine tuberculosis"
* #BOVINE_VIRAL_DIARRHOEA "Bovine viral diarrhoea"
* #BRUCELLOSIS "Brucellosis"
* #BRUCELLOSIS_BRUCELLA_ABORTUS "Brucellosis (Brucella abortus)"
* #BRUCELLOSIS_BRUCELLA_MELITENSIS "Brucellosis (Brucella melitensis)"
* #BRUCELLOSIS_BRUCELLA_SUIS "Brucellosis (Brucella suis)"
* #CAMELPOX "Camelpox"
* #CAMPYLOBACTERIOSIS "Campylobacteriosis"
* #CANINE_DISTEMPER "Canine distemper"
* #CAPRINE_ARTHRITIS_ENCEPHALITIS "Caprine arthritis/encephalitis"
* #CAT_FLUE "Cat flue"
* #CHANNEL_CATFISH_VIRUS_DISEASE "Channel catfish virus disease"
* #CHILL_BROOD "Chill brood"
* #CHONDROCOCCUS_COLUMNARIS_FINS_EROSION "Chondrococcus columnaris/fins erosion"
* #CHRONIC_RESPIRATORY_DISEASE "Chronic respiratory disease"
* #CHRONIC_WASTING_DISEASE "Chronic wasting disease"
* #CLASSICAL_SWINE_FEVER "Classical swine fever"
* #COCCIDIOSIS "Coccidiosis"
* #COLIBACILLOSIS "Colibacillosis"
* #COLONY_COLLAPSE "Colony Collapse"
* #CONTAGIOUS_AGALACTIA "Contagious agalactia"
* #CONTAGIOUS_BOVINE_PLEUROPNEUMONIA "Contagious bovine pleuropneumonia"
* #CONTAGIOUS_CAPRINE_PLEUROPNEUMONIA "Contagious caprine pleuropneumonia"
* #CONTAGIOUS_ECTHYMA "Contagious Ecthyma"
* #CONTAGIOUS_EQUINE_ANEMIA "Contagious Equine Anemia"
* #CONTAGIOUS_EQUINE_METRITIS "Contagious equine metritis"
* #COVID19_SARSCOV2 "COVID-19 (SARS-COV-2)"
* #CRAYFISH_PLAGUE_APHANOMYCES_ASTACI "Crayfish plague (Aphanomyces astaci)"
* #CRIMEAN_CONGO_HAEMORRHAGIC_FEVER "Crimean Congo haemorrhagic fever"
* #CYSTICERCOSIS "Cysticercosis"
* #DENGUE "Dengue"
* #DERMATOPHILOSIS "Dermatophilosis"
* #DISTEMPER "Distemper"
* #DISTOMATOSIS "Distomatosis"
* #DOURINE "Dourine"
* #DRACUNCULIASIS "Dracunculiasis"
* #DUCK_VIRUS_ENTERITIS "Duck virus enteritis"
* #DUCK_VIRUS_HEPATITIS "Duck virus hepatitis"
* #DYSTOCIA "Dystocia"
* #EAST_COAST_FEVER "East Coast fever"
* #EASTERN_EQUINE_ENCEPHALOMYELITIS "Eastern equine encephalomyelitis"
* #EBOLARESTON "Ebola-Reston"
* #EBOLA_VIRUS "Ebola Virus"
* #ECHINOCOCCOSIS_HYDATIDOSIS "Echinococcosis/hydatidosis"
* #ECTOPARASITISM "Ectoparasitism"
* #EGG_DROP_SYNDROME "Egg Drop Syndrome"
* #ENTERIC_SEPTICAEMIA_CATFISH_EDWARDSIELLA_ICTALURI "Enteric septicaemia of catfish (Edwardsiella ictaluri)"
* #ENTEROTOXEMIA "Enterotoxemia"
* #ENZOOTIC_ABORTION_CHLAMYDIOSIS "Enzootic abortion (chlamydiosis)"
* #ENZOOTIC_ABORTION_OF_EWES_OVINE_CHLAMYDIOSIS "Enzootic abortion of ewes (ovine chlamydiosis)"
* #ENZOOTIC_BOVINE_LEUKOSIS "Enzootic bovine leukosis"
* #EPHEMERAL_FEVER_3_DAY_STIFFNESS "Ephemeral fever (3 day stiffness)"
* #EPIZOOTIC_HAEMATOPOIETIC_NECROSIS "Epizootic haematopoietic necrosis"
* #EPIZOOTIC_HAEMORRHAGIC_DISEASE "Epizootic haemorrhagic disease"
* #EPIZOOTIC_LYMPHANGITIS "Epizootic lymphangitis"
* #EPIZOOTIC_ULCERATIVE_SYNDROME "Epizootic ulcerative syndrome"
* #EQUID_HERPRESVIRUS1_EHV1 "Equid herpresvirus1 (EHV-1)"
* #EQUINE_ENCEPHALOMYELITIS_EAST_AND_WEST "Equine Encephalomyelitis (East and West)"
* #EQUINE_ENCEPHALOMYELITIS_EASTERN "Equine encephalomyelitis (Eastern)"
* #EQUINE_ENCEPHALOMYELITIS_WESTERN "Equine encephalomyelitis (Western)"
* #EQUINE_ENCEPHALOSIS "Equine encephalosis"
* #EQUINE_INFECTIOUS_ANAEMIA "Equine infectious anaemia"
* #EQUINE_LYMPHANGITIS "Equine lymphangitis"
* #EQUINE_PIROPLASMOSIS "Equine piroplasmosis"
* #EQUINE_RHINOPNEUMONITIS "Equine rhinopneumonitis"
* #EQUINE_VIRAL_ARTERITIS "Equine viral arteritis"
* #ERHLICHIOSIS "Erhlichiosis"
* #ERYSIPELAS "Erysipelas"
* #ESCHERICHIA_COLI "Escherichia coli"
* #EUROPEAN_FOULBROOD_OF_HONEY_BEES "European foulbrood of honey bees"
* #FOOD_BORNE_DISEASE "Food borne disease"
* #FOOT_AND_MOUTH_DISEASE "Foot and mouth disease"
* #FOOT_ROT "Foot rot"
* #FOULBROOD_OF_HONEY "Foulbrood of honey"
* #FOWL_CHOLERA "Fowl cholera"
* #FOWL_POX "Fowl pox"
* #FOWL_TYPHOID "Fowl typhoid"
* #FUSARIUM_SPP "Fusarium spp"
* #GLANDERS "Glanders"
* #GREGARINE_INFECTION "Gregarine infection"
* #GYRODACTYLOSIS_GYRODACTYLUS_SALARIS "Gyrodactylosis (Gyrodactylus salaris)"
* #HAEMORRHAGIC_SEPTICAEMIA "Haemorrhagic Septicaemia"
* #HALIPHTHOROS_SPPS "Haliphthoros spps"
* #HALOCRSTCIDA_SPP "Halocrstcida spp"
* #HEARTWATER "Heartwater"
* #HELMINTHIASIS "Helminthiasis"
* #HENDRA_VIRUS_DISEASE "Hendra Virus Disease"
* #HEPATITIS "Hepatitis"
* #HERNIE_EMBILICAL "Hernie Embilical"
* #HORSE_POX "Horse pox"
* #INFECTION_WITH_HAPLOSPORIDIUM_NELSONI "Infection with Haplosporidium nelsoni"
* #INFECTION_WITH_MARTEILIA_REFRINGENS "Infection with Marteilia refringens"
* #INFECTION_WITH_MARTEILIA_SYDNEYI "Infection with Marteilia sydneyi"
* #INFECTION_WITH_PERKINSUS_MARINUS "Infection with Perkinsus marinus"
* #INFECTION_WITH_XENOHALIOTIS_CALIFORNIENSIS "Infection with Xenohaliotis californiensis"
* #INFECTIOUS_BOVINE_KERATOCONJUNCTIVITIS_PINKEYE "Infectious Bovine Keratoconjunctivitis (Pinkeye)"
* #INFECTIOUS_BOVINE_RHINOTRACHEITIS "Infectious bovine rhinotracheitis"
* #INFECTIOUS_BRONCHITIS "Infectious Bronchitis"
* #INFECTIOUS_BURSAL_DISEASE_GUMBORO_DISEASE "Infectious bursal disease (Gumboro disease)"
* #INFECTIOUS_CORYZA "Infectious Coryza"
* #INFECTIOUS_HAEMATOPOIETIC_NECROSIS "Infectious haematopoietic necrosis"
* #IHHN "Infectious hypodermal and haematopoietic necrosis (IHHN)"
* #INFECTIOUS_MYONECROSIS "Infectious myonecrosis"
* #INFECTIOUS_PUSTULAR_VULVOVAGINITIS "Infectious pustular vulvovaginitis"
* #INFECTIOUS_SALMON_ANAEMIA "Infectious salmon anaemia"
* #INFLUENZA_AVIAN "Influenza - Avian"
* #INFLUENZA_EQUINE "Influenza - Equine"
* #INFLUENZA_SWINE "Influenza - Swine"
* #INTOXICATION "Intoxication"
* #JAPANESE_ENCEPHALITIS "Japanese Encephalitis"
* #KOI_HERPES_VIRUS_KHV_DISEASE "Koi herpes virus (KHV) disease"
* #KUNJIN_VIRUS "Kunjin virus"
* #KYASANUR_FOREST_DISEASE "Kyasanur forest disease"
* #LAAGENIDIUM_SPP "Laagenidium spp"
* #LASSA_FEVER "Lassa fever"
* #LEISHMANIOSIS "Leishmaniosis"
* #LEPROSY_HANSEN'S_DISEASE "Leprosy (Hansen's disease)"
* #LEPTOSPIROSIS "Leptospirosis"
* #LISTERIOSIS "Listeriosis"
* #LIVESTOCK_PARASITIC_DISEASES "Livestock parasitic diseases"
* #LUMINESCENT_BACTERIAL_DISEASES "Luminescent bacterial diseases"
* #LUMPY_SKIN_DISEASE "Lumpy skin disease"
* #LUMPY_WOOL_DERMATOPHILUS "Lumpy wool (Dermatophilus)"
* #MAEDIVISNA "Maedi-visna"
* #MALIGNANT_CATARRHAL_FEVER "Malignant catarrhal fever"
* #MANGE "Mange"
* #MARBURG_HEMORRHAGIC_FEVER "Marburg Hemorrhagic Fever"
* #MAREK'S_DISEASE "Marek's disease"
* #MASTITIS "Mastitis"
* #MERSCOV "MERS-CoV"
* #MICROSPORIDIAN_INFECTION "Microsporidian infection"
* #MIKROCYTOS_MACKINI "Mikrocytos mackini"
* #MONKEY_POX "Monkey Pox"
* #MORBILLIVIRUSES "Morbilliviruses  (esp. Peste des Petits Ruminants and Rinderpest)"
* #MUSCLE_NECROSIS_VIRUS "Muscle necrosis virus"
* #MYXOMATOSIS "Myxomatosis"
* #NAIROBI_SHEEP_DISEASE "Nairobi sheep disease"
* #NECROTISING_HEPATOPANCREATIS "Necrotising hepatopancreatis"
* #NEWCASTLE_DISEASE "Newcastle disease"
* #NEW_WORLD_SCREWWORM_COCHLIOMYIA_HOMINIVORAX "New world screwworm (Cochliomyia hominivorax)"
* #NIPAH_VIRUS_ENCEPHALITIS "Nipah virus encephalitis"
* #OLD_WORLD_SCREWWORM_CHRYSOMYA_BEZZIANA "Old world screwworm (Chrysomya bezziana)"
* #OMPHALOPHLEBITIS_NAVEL_ILL_JOINT_ILL "Omphalophlebitis (Navel ill- Joint ill)"
* #ONCORHYNCHUS_MASOU_VIRUS_DISEASE "Oncorhynchus masou virus disease"
* #ORF "Orf"
* #ORMILO_ENCEPHALITIS_THELIRIOSIS "Ormilo/Encephalitis theliriosis"
* #OTHER_BACTERIAL_DISEASES "Other bacterial diseases"
* #OTHER_OPPORTUNISSTIC_BACTERIAL_PATHOGEN "Other opportunisstic bacterial pathogen"
* #OVINE_EPIDIDYMITIS_BRUCELLA_OVIS "Ovine epididymitis (Brucella ovis)"
* #OVINE_PULMONARY_ADENOMATOSIS "Ovine pulmonary adenomatosis"
* #PAPILLOMA_VIRUS_WARDS "Papilloma Virus (wards)"
* #PARAPHIMOSIS "Paraphimosis"
* #PARATUBERCULOSIS "Paratuberculosis"
* #PARVOVIRUS "Parvovirus"
* #PERITRICH_CILIATES "Peritrich ciliates"
* #PESTE_DES_PETITS_RUMINANTS "Peste des petits ruminants"
* #PHIMOSIS "Phimosis"
* #PLAGUE "Plague"
* #POISONING "Poisoning"
* #POLIOVIRUS "Poliovirus"
* #PORCINE_CYSTICERCOSIS "Porcine cysticercosis"
* #PORCINE_ENTEROVIRAL_ENCEPHALOMYELITIS "Porcine Enteroviral encephalomyelitis"
* #PORCINE_EPIDEMIC_DIARRHEA "Porcine epidemic diarrhea"
* #PORCINE_REPRODUCTIVE_AND_RESPIRATORY_SYNDROME "Porcine reproductive and respiratory syndrome"
* #POSTWEANING_MULTISYSTEMIC_WASTING_SYNDROME_PMWS "Postweaning Multisystemic Wasting Syndrome (PMWS)"
* #PSITTACOSISCHLAMYDOPHILA_PSITTACI "Psittacosis(Chlamydophila psittaci)"
* #PULLORUM_DISEASE "Pullorum disease"
* #Q_FEVER "Q fever"
* #RABBIT_HAEMORRHAGIC_DISEASE "Rabbit haemorrhagic disease"
* #RABIES "Rabies"
* #RANAVIRUS "Ranavirus"
* #RED_SEA_BREAM_IRIDOVIRAL_DISEASE "Red sea bream iridoviral disease"
* #RED_STERNUM_SYNDROME "Red sternum syndrome"
* #REOVIRUS "Reovirus"
* #RICKETTSIOSIS "Rickettsiosis"
* #RIFT_VALLEY_FEVER "Rift Valley fever"
* #RINDERPEST "Rinderpest"
* #RUMINANT_MYCOPLASMOSES "Ruminant Mycoplasmoses"
* #SALMONELLOSIS_S_ABORTUSOVIS "Salmonellosis (S. abortusovis)"
* #SALMONID_ALPHAVIRUS "Salmonid alphavirus"
* #SCHMALLENBERG "Schmallenberg"
* #SCRAPIE "Scrapie"
* #SHEEP_POX_AND_GOAT_POX "Sheep pox and goat pox"
* #SMALL_HIVE_BEETLE_INFESTATION_AETHINA_TUMIDA "Small hive beetle infestation (Aethina tumida)"
* #SPHERICAL_BACULOVIROSIS "Spherical baculovirosis (Penaeus monodon-type baculovirus)"
* #SPRING_VIRAEMIA_OF_CARP "Spring viraemia of carp"
* #STARVATION "Starvation"
* #STRANGLES "Strangles"
* #STREPTOCOCCUS_SUIS "Streptococcus suis"
* #SUCTORIAN_CILIATES "Suctorian ciliates"
* #SURRA_TRYPANOSOMA_EVANSI "Surra (Trypanosoma evansi)"
* #SUSPECTED_NEW_EMERGING_DISEASE "Suspected New Emerging Disease"
* #SWINE_DYSENTRY "Swine dysentry"
* #SWINE_INFLUENZA "Swine influenza"
* #SWINE_NOVEL_ENTERIC_CORONA_VIRUS_DISEASE "Swine Novel Enteric Corona Virus disease"
* #SWINE_VESICULAR_DISEASE "Swine vesicular disease"
* #TAURA_SYNDROME "Taura syndrome"
* #TESCHOVIRUS_ENCEPHALOMYELITIS "Teschovirus encephalomyelitis"
* #TETANUS "Tetanus"
* #TETRAHEDRAL_BACULOVIROSIS_BACULOVIRUS_PENAEI "Tetrahedral baculovirosis (Baculovirus penaei)"
* #THEILERIOSIS "Theileriosis"
* #THIRD_EYELID_PROLAPSE "Third eyelid prolapse"
* #THREE_DAYS_SICKNESS "Three days sickness"
* #TICKBORNE_ENCEPHALITIS "Tick-borne encephalitis"
* #TOXOPLASMOSIS "Toxoplasmosis"
* #TRANSMISSIBLE_GASTROENTERITIS "Transmissible gastroenteritis"
* #TRANSMISSIBLE_VENEREAL_TUMOR_TVT "Transmissible venereal tumor (TVT)"
* #TRAUMA_INJURY_FRACTURE "Trauma/injury/fracture"
* #TRAUMATIC_RETICULOPERICARDITIS "Traumatic Reticulopericarditis"
* #TRICHINELLOSIS "Trichinellosis"
* #TRICHOMONOSIS "Trichomonosis"
* #TROPILAELAPS_INFESTATION_OF_HONEY_BEES "Tropilaelaps infestation of honey bees"
* #TRYPANOSOMOSIS_TSETSETRANSMITTED "Trypanosomosis (tsetse-transmitted)"
* #TUBERCULOSIS "Tuberculosis"
* #TULAREMIA "Tularemia"
* #TURKEY_RHINOTRACHEITIS "Turkey rhinotracheitis"
* #UNKNOWN_DISEASE "Unknown disease"
* #UTERINE_PROLAPSE "Uterine Prolapse"
* #VARROA_MITES "Varroa mites"
* #VARROOSIS_OF_HONEY_BEES "Varroosis of honey bees"
* #VECTORBORNE_DISEASES "Vector-borne diseases"
* #VENEZUELAN_EQUINE_ENCEPHALOMYELITIS "Venezuelan equine encephalomyelitis"
* #VESICULAR_STOMATITIS "Vesicular stomatitis"
* #VIBRIO_ALGINOLYTICUS "Vibrio alginolyticus"
* #VIBRIO_ANGUILLARUM_RED_SORTED_DISEASE "Vibrio anguillarum/Red sorted disease"
* #VIBRIO_HARVEYI "Vibrio harveyi"
* #VIBRIO_PARAHEMOLYTCUS_SCALE_DISEASES "Vibrio parahemolytcus/ scale diseases"
* #VIRAL_ENCEPHALOPATHY_AND_RETINOPATHY "Viral encephalopathy and retinopathy"
* #VIRAL_HAEMORRHAGIC_FEVERS "Viral Haemorrhagic Fevers"
* #VIRAL_HAEMORRHAGIC_SEPTICAEMIA "Viral haemorrhagic septicaemia"
* #WAX_MOTHS "Wax moths"
* #WESTERN_EQUINE_ENCEPHALOMYELITIS "Western equine encephalomyelitis"
* #WEST_NILE_FEVER "West Nile Fever"
* #WHITE_SPOT_DISEASE "White spot disease"
* #WHITE_SPOT_SYNDROME_VIRUS "White spot syndrome virus"
* #WHITE_TAIL_DISEASE "White tail disease"
* #WOUND_ABCESS "Wound/Abcess"
* #YELLOW_FEVER "Yellow fever"
* #YELLOW_HEAD_DISEASE "Yellow head disease"
* #YEZO_VIRUS "Yezo virus"